# Generated by Django 6.0 on 2026-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INR", "INR"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("JPY", "JPY"),
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CNY", "CNY"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
    ]
