# Generated by Django 6.0 on 2026-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeedImagePoolItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_slug", models.SlugField(max_length=120)),
                ("s3_key", models.CharField(max_length=500, unique=True)),
                ("image_url", models.URLField()),
                (
                    "source_url",
                    models.URLField(
                        help_text="Original Pexels photo page, kept for reference/attribution."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category_slug", "id"],
            },
        ),
    ]
