# Generated by Django 6.0 on 2026-07-14 14:39

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def enable_pgvector(apps, schema_editor):
    # SQLite (the forced test DB, see settings.py) has no CREATE EXTENSION
    # concept and no vector type of its own - VectorField degrades to a
    # plain text column there, which is enough for ORM-level tests, but this
    # extension step is meaningless (and would error) outside Postgres.
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def disable_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP EXTENSION IF EXISTS vector")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_product_seo_keywords"),
    ]

    operations = [
        migrations.RunPython(enable_pgvector, disable_pgvector),
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=512)),
                (
                    "model_id",
                    models.CharField(default="voyage-4-lite-512", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
