# Generated by Django 6.0 on 2026-07-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_rename_buyer_to_user_conversation"),
        ("products", "0003_product_seo_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="products.product",
            ),
        ),
    ]
