# Generated by Django 6.0 on 2026-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_created_at_alter_product_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seo_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
